DROP TABLE IF EXISTS users, categories, events, compilations, compilation_events, locations, comments CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                 NOT NULL,
    email              VARCHAR(255)                                            NOT NULL,
    name               VARCHAR(255)                                            NOT NULL,
    CONSTRAINT PK_USER                PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL          UNIQUE      (email)
);

CREATE TABLE IF NOT EXISTS categories (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                 NOT NULL,
    name               VARCHAR(50)                                             NOT NULL,
    CONSTRAINT PK_CATEGORY            PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME       UNIQUE      (name)
);

CREATE TABLE IF NOT EXISTS locations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    lat                FLOAT                                                    NOT NULL,
    lon                FLOAT                                                    NOT NULL,
    CONSTRAINT PK_LOCATION PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    pinned             BOOLEAN DEFAULT false                                    NOT NULL,
    title              VARCHAR(50)                                              NOT NULL,
    CONSTRAINT PK_COMPILATION PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                 NOT NULL,
    annotation         VARCHAR(2000)                                           NOT NULL,
    category_id        BIGINT                                                  NOT NULL,
    description        VARCHAR(7000)                                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                             NOT NULL,
    location_id        BIGINT                                                  NOT NULL,
    paid               BOOLEAN DEFAULT false                                   NOT NULL,
    participant_limit  INT DEFAULT 0                                           NOT NULL,
    confirmed_requests INT,
    request_moderation BOOLEAN DEFAULT true                                    NOT NULL,
    title              VARCHAR(120)                                            NOT NULL,
    initiator_id       BIGINT                                                  NOT NULL,
    state              VARCHAR(9) DEFAULT 'PENDING'                            NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE                             NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_EVENT                PRIMARY KEY (id),
    CONSTRAINT FK_EVENTS_ON_CATEGORIES FOREIGN KEY (category_id)  REFERENCES categories (id) ON DELETE NO ACTION,
    CONSTRAINT FK_EVENTS_ON_LOCATIONS  FOREIGN KEY (location_id)  REFERENCES locations  (id) ON DELETE CASCADE,
    CONSTRAINT FK_EVENTS_ON_USERS      FOREIGN KEY (initiator_id) REFERENCES users      (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    event_id           BIGINT                                                   NOT NULL,
    requester_id       BIGINT                                                   NOT NULL,
    status             VARCHAR(255) DEFAULT 'PENDING'                           NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE                              NOT NULL,
    CONSTRAINT PK_REQUEST            PRIMARY KEY (id),
    CONSTRAINT FK_REQUESTS_ON_EVENTS FOREIGN KEY (event_id)       REFERENCES events (id)      ON DELETE CASCADE,
    CONSTRAINT FK_REQUESTS_ON_USERS  FOREIGN KEY (requester_id)   REFERENCES users  (id)      ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id     BIGINT                                                   NOT NULL,
    event_id           BIGINT                                                   NOT NULL,
    CONSTRAINT PK_COMPILATION_EVENTS PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT FK_CE_ON_COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    CONSTRAINT FK_CE_ON_EVENTS       FOREIGN KEY (event_id)       REFERENCES events       (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    content            VARCHAR(2000)                                            NOT NULL,
    created            TIMESTAMP                                                NOT NULL,
    updated            TIMESTAMP,
    event_id           BIGINT                                                   NOT NULL,
    author_id          BIGINT                                                   NOT NULL,
    CONSTRAINT PK_COMMENT PRIMARY KEY (id),
    CONSTRAINT FK_EVENTS_ON_COMMENTS FOREIGN KEY (event_id)      REFERENCES events (id)         ON DELETE CASCADE,
    CONSTRAINT FK_USERS_ON_COMMENTS  FOREIGN KEY (author_id)     REFERENCES users  (id)         ON DELETE CASCADE
);