DROP TABLE IF EXISTS stats CASCADE;
CREATE TABLE IF NOT EXISTS stats (
    id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app       VARCHAR(255)                                           NOT NULL,
    uri       VARCHAR(255)                                           NOT NULL,
    ip        VARCHAR(32)                                            NOT NULL,
    CREATED TIMESTAMP WITHOUT TIME ZONE                              NOT NULL
);